"""
Training recorder to capture model states during training for video generation.

This file was generated by Cursor.
"""


class TrainingRecorder:
    """Records model states during training for visualization."""
    
    def __init__(self, record_every_n_epochs=1):
        """
        Args:
            record_every_n_epochs: Record state every N epochs (1 = every epoch)
        """
        self.record_every_n_epochs = record_every_n_epochs
        self.history = []
        self.current_epoch = 0
    
    def record(self, model, epoch, loss, accuracy=None, **kwargs):
        """Record model state at current epoch."""
        if epoch % self.record_every_n_epochs == 0:
            state = {
                'epoch': epoch,
                'loss': loss,
                'accuracy': accuracy,
            }
            
            # Save model parameters
            state['model_state'] = {}
            for i, layer in enumerate(model.layers):
                if hasattr(layer, 'W'):
                    state['model_state'][f'layer_{i}_W'] = layer.W.copy()
                if hasattr(layer, 'b'):
                    state['model_state'][f'layer_{i}_b'] = layer.b.copy()
            
            # Save any additional metrics
            state.update(kwargs)
            
            self.history.append(state)
        
        self.current_epoch = epoch
    
    def get_state_at_epoch(self, epoch):
        """Get recorded state at specific epoch."""
        for state in self.history:
            if state['epoch'] == epoch:
                return state
        return None
    
    def restore_model_state(self, model, epoch):
        """Restore model to state at specific epoch."""
        state = self.get_state_at_epoch(epoch)
        if state is None:
            return False
        
        for i, layer in enumerate(model.layers):
            if hasattr(layer, 'W') and f'layer_{i}_W' in state['model_state']:
                layer.W = state['model_state'][f'layer_{i}_W'].copy()
            if hasattr(layer, 'b') and f'layer_{i}_b' in state['model_state']:
                layer.b = state['model_state'][f'layer_{i}_b'].copy()
        
        return True
    
    def get_all_epochs(self):
        """Get list of all recorded epochs."""
        return [state['epoch'] for state in self.history]

